version: "3.7"
services:

  front-envoy:
    build:
      context: .
      dockerfile: Dockerfile-frontenvoy
    networks:
    - envoymesh
    ports:
    - "8080:8080"
    - "8443:8443"
    - "8001:8001"

  service1:
    build:
      context: .
      dockerfile: Dockerfile-service1
    volumes:
    - ./service-envoy.yaml:/etc/service-envoy.yaml
    networks:
    - envoymesh
    environment:
    - SERVICE_NAME=1

  service2:
    build:
      context: .
      dockerfile: Dockerfile-service2
    volumes:
    - ./service-envoy.yaml:/etc/service-envoy.yaml
    networks:
    - envoymesh
    environment:
    - SERVICE_NAME=2

  service3:
    build:
      context: .
      dockerfile: Dockerfile-service3
    volumes:
    - ./service-envoy.yaml:/etc/service-envoy.yaml
    networks:
    - envoymesh
    environment:
    - SERVICE_NAME=3

networks:
  envoymesh: {}
